export const INVENTORY_MOVEMENT_TYPES = {
  FULL_OUT: "FULL_OUT",
  EMPTY_IN: "EMPTY_IN",
  LOAN_OUT: "LOAN_OUT",
  LOAN_RETURN: "LOAN_RETURN",
  ADJUSTMENT: "ADJUSTMENT"
} as const;

export const LOAN_STATUSES = {
  BORROWED: "BORROWED",
  PARTIAL_RETURNED: "PARTIAL_RETURNED",
  RETURNED: "RETURNED",
  OVERDUE: "OVERDUE",
  CANCELLED: "CANCELLED"
} as const;
