export const LOAN_STATUSES = {
  BORROWED: "BORROWED",
  PARTIAL_RETURNED: "PARTIAL_RETURNED",
  RETURNED: "RETURNED",
  OVERDUE: "OVERDUE",
  CANCELLED: "CANCELLED"
} as const;

export type LoanStatus = (typeof LOAN_STATUSES)[keyof typeof LOAN_STATUSES];

export const ACTIVE_LOAN_STATUSES = [
  LOAN_STATUSES.BORROWED,
  LOAN_STATUSES.PARTIAL_RETURNED,
  LOAN_STATUSES.OVERDUE
] as const;

export const RETURNABLE_LOAN_STATUSES = ACTIVE_LOAN_STATUSES;

export const FINAL_LOAN_STATUSES = [
  LOAN_STATUSES.RETURNED,
  LOAN_STATUSES.CANCELLED
] as const;
