export const TRANSACTION_TYPES = {
  DELIVERY_EXCHANGE: "DELIVERY_EXCHANGE",
  WALK_IN_EXCHANGE: "WALK_IN_EXCHANGE",
  BORROW_CYLINDER: "BORROW_CYLINDER",
  RETURN_CYLINDER: "RETURN_CYLINDER",
  BUY_FULL_TANK: "BUY_FULL_TANK"
} as const;

export type TransactionType = (typeof TRANSACTION_TYPES)[keyof typeof TRANSACTION_TYPES];

export const PRICED_CREATE_TRANSACTION_TYPES = [
  TRANSACTION_TYPES.DELIVERY_EXCHANGE,
  TRANSACTION_TYPES.WALK_IN_EXCHANGE,
  TRANSACTION_TYPES.BORROW_CYLINDER,
  TRANSACTION_TYPES.BUY_FULL_TANK
] as const;

export type PricedCreateTransactionType = (typeof PRICED_CREATE_TRANSACTION_TYPES)[number];
