export const TRANSACTION_TYPES = {
  DELIVERY_EXCHANGE: "DELIVERY_EXCHANGE",
  WALK_IN_EXCHANGE: "WALK_IN_EXCHANGE",
  BORROW_CYLINDER: "BORROW_CYLINDER",
  RETURN_CYLINDER: "RETURN_CYLINDER",
  BUY_FULL_TANK: "BUY_FULL_TANK"
} as const;

export const TRANSACTION_STATUSES = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
} as const;

export const ITEM_ACTIONS = {
  EXCHANGE: "EXCHANGE",
  BORROW: "BORROW",
  RETURN: "RETURN",
  BUY_FULL_TANK: "BUY_FULL_TANK"
} as const;

export const VALID_STATUS_TRANSITIONS: Record<string, string[]> = {
  PENDING: ["IN_PROGRESS", "CANCELLED"],
  IN_PROGRESS: ["COMPLETED", "CANCELLED"],
  COMPLETED: [],
  CANCELLED: []
};
