export const TRANSACTION_TYPES = {
  DELIVERY_EXCHANGE: "DELIVERY_EXCHANGE",
  WALK_IN_EXCHANGE: "WALK_IN_EXCHANGE",
  BORROW_CYLINDER: "BORROW_CYLINDER",
  RETURN_CYLINDER: "RETURN_CYLINDER",
  BUY_FULL_TANK: "BUY_FULL_TANK"
} as const;

export type TransactionType = (typeof TRANSACTION_TYPES)[keyof typeof TRANSACTION_TYPES];

export const PRICED_CREATE_TRANSACTION_TYPES = [
  TRANSACTION_TYPES.DELIVERY_EXCHANGE,
  TRANSACTION_TYPES.WALK_IN_EXCHANGE,
  TRANSACTION_TYPES.BORROW_CYLINDER,
  TRANSACTION_TYPES.BUY_FULL_TANK
] as const;

export type PricedCreateTransactionType = (typeof PRICED_CREATE_TRANSACTION_TYPES)[number];

export const TRANSACTION_STATUSES = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
} as const;

export type TransactionStatus = (typeof TRANSACTION_STATUSES)[keyof typeof TRANSACTION_STATUSES];

export const ITEM_ACTIONS = {
  EXCHANGE: "EXCHANGE",
  BORROW: "BORROW",
  RETURN: "RETURN",
  BUY_FULL_TANK: "BUY_FULL_TANK"
} as const;

export type ItemAction = (typeof ITEM_ACTIONS)[keyof typeof ITEM_ACTIONS];

export const FINAL_TRANSACTION_STATUSES = [
  TRANSACTION_STATUSES.COMPLETED,
  TRANSACTION_STATUSES.CANCELLED
] as const;

export const ALLOWED_STATUS_TRANSITIONS: Readonly<Record<TransactionStatus, readonly TransactionStatus[]>> = {
  [TRANSACTION_STATUSES.PENDING]: [TRANSACTION_STATUSES.IN_PROGRESS, TRANSACTION_STATUSES.CANCELLED],
  [TRANSACTION_STATUSES.IN_PROGRESS]: [TRANSACTION_STATUSES.COMPLETED, TRANSACTION_STATUSES.CANCELLED],
  [TRANSACTION_STATUSES.COMPLETED]: [],
  [TRANSACTION_STATUSES.CANCELLED]: []
};

export const INITIAL_STATUS_BY_TRANSACTION_TYPE: Readonly<Record<TransactionType, TransactionStatus>> = {
  [TRANSACTION_TYPES.DELIVERY_EXCHANGE]: TRANSACTION_STATUSES.PENDING,
  [TRANSACTION_TYPES.WALK_IN_EXCHANGE]: TRANSACTION_STATUSES.COMPLETED,
  [TRANSACTION_TYPES.BORROW_CYLINDER]: TRANSACTION_STATUSES.COMPLETED,
  [TRANSACTION_TYPES.RETURN_CYLINDER]: TRANSACTION_STATUSES.COMPLETED,
  [TRANSACTION_TYPES.BUY_FULL_TANK]: TRANSACTION_STATUSES.COMPLETED
};

export const ITEM_ACTION_BY_TRANSACTION_TYPE: Readonly<Record<TransactionType, ItemAction>> = {
  [TRANSACTION_TYPES.DELIVERY_EXCHANGE]: ITEM_ACTIONS.EXCHANGE,
  [TRANSACTION_TYPES.WALK_IN_EXCHANGE]: ITEM_ACTIONS.EXCHANGE,
  [TRANSACTION_TYPES.BORROW_CYLINDER]: ITEM_ACTIONS.BORROW,
  [TRANSACTION_TYPES.RETURN_CYLINDER]: ITEM_ACTIONS.RETURN,
  [TRANSACTION_TYPES.BUY_FULL_TANK]: ITEM_ACTIONS.BUY_FULL_TANK
};

export { LOAN_STATUSES } from "./loan.constants";
